/**
 * Created by Oleksandr Lisovyk on 01.11.2016.
 */
'use strict';

export default {
    LOADER_ON: 'LOADER_ON',
    LOADER_OFF: 'LOADER_OFF',
    LOGIN_DONE: 'LOGIN_DONE',
    ADD_MESSAGE: 'ADD_MESSAGE',
    REMOVE_MESSAGE: 'REMOVE_MESSAGE',
    ADD_PUZZLE: 'ADD_PUZZLE',
    EDIT_PUZZLE: 'EDIT_PUZZLE',
    REMOVE_PUZZLE: 'REMOVE_PUZZLE',
    LOAD_PUZZLES: 'LOAD_PUZZLES',
    LOAD_PUZZLE: 'LOAD_PUZZLE'
};